version: '3'
services:
  lowcode-docusaurus:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    working_dir: /app
    command: npm run serve -- --host 0.0.0.0 --port 4000
