// Mocks generated by Mockito 5.4.6 from annotations
// in mamoai/test/features/view_screen/application/usecases/get_incident_items_usecase_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:dartz/dartz.dart' as _i2;
import 'package:mamoai/core/error/failures.dart' as _i5;
import 'package:mamoai/features/view_screen/domain/entities/incident_item.dart'
    as _i6;
import 'package:mamoai/features/view_screen/domain/entities/incident_status.dart'
    as _i7;
import 'package:mamoai/features/view_screen/domain/repositories/i_view_screen_repository.dart'
    as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [IViewScreenRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockIViewScreenRepository extends _i1.Mock
    implements _i3.IViewScreenRepository {
  MockIViewScreenRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i6.IncidentItem>>>
  getIncidentItems() =>
      (super.noSuchMethod(
            Invocation.method(#getIncidentItems, []),
            returnValue:
                _i4.Future<
                  _i2.Either<_i5.Failure, List<_i6.IncidentItem>>
                >.value(
                  _FakeEither_0<_i5.Failure, List<_i6.IncidentItem>>(
                    this,
                    Invocation.method(#getIncidentItems, []),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, List<_i6.IncidentItem>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.IncidentItem>> getIncidentItemById(
    String? id,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getIncidentItemById, [id]),
            returnValue:
                _i4.Future<_i2.Either<_i5.Failure, _i6.IncidentItem>>.value(
                  _FakeEither_0<_i5.Failure, _i6.IncidentItem>(
                    this,
                    Invocation.method(#getIncidentItemById, [id]),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, _i6.IncidentItem>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.IncidentItem>> updateIncidentStatus({
    required String? id,
    required _i7.IncidentStatus? newStatus,
    required String? actionType,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#updateIncidentStatus, [], {
              #id: id,
              #newStatus: newStatus,
              #actionType: actionType,
            }),
            returnValue:
                _i4.Future<_i2.Either<_i5.Failure, _i6.IncidentItem>>.value(
                  _FakeEither_0<_i5.Failure, _i6.IncidentItem>(
                    this,
                    Invocation.method(#updateIncidentStatus, [], {
                      #id: id,
                      #newStatus: newStatus,
                      #actionType: actionType,
                    }),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, _i6.IncidentItem>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.IncidentItem>> toggleAlertStatus({
    required String? id,
    required bool? isActive,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#toggleAlertStatus, [], {
              #id: id,
              #isActive: isActive,
            }),
            returnValue:
                _i4.Future<_i2.Either<_i5.Failure, _i6.IncidentItem>>.value(
                  _FakeEither_0<_i5.Failure, _i6.IncidentItem>(
                    this,
                    Invocation.method(#toggleAlertStatus, [], {
                      #id: id,
                      #isActive: isActive,
                    }),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, _i6.IncidentItem>>);
}
