// Mocks generated by Mockito 5.4.6 from annotations
// in frontend/test/features/history/presentation/blocs/history/history_bloc_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:frontend/features/history/domain/entities/incident.dart' as _i2;
import 'package:frontend/features/history/domain/repositories/i_incident_repository.dart'
    as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeIncident_0 extends _i1.SmartFake implements _i2.Incident {
  _FakeIncident_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [IIncidentRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockIIncidentRepository extends _i1.Mock
    implements _i3.IIncidentRepository {
  MockIIncidentRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<List<_i2.Incident>> fetchIncidents({
    int? limit = 20,
    int? offset = 0,
    String? orderBy = 'detectedAt',
    bool? descending = true,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#fetchIncidents, [], {
              #limit: limit,
              #offset: offset,
              #orderBy: orderBy,
              #descending: descending,
            }),
            returnValue: _i4.Future<List<_i2.Incident>>.value(<_i2.Incident>[]),
          )
          as _i4.Future<List<_i2.Incident>>);

  @override
  _i4.Future<_i2.Incident> fetchIncidentById(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#fetchIncidentById, [id]),
            returnValue: _i4.Future<_i2.Incident>.value(
              _FakeIncident_0(
                this,
                Invocation.method(#fetchIncidentById, [id]),
              ),
            ),
          )
          as _i4.Future<_i2.Incident>);

  @override
  _i4.Future<List<_i2.Incident>> searchIncidents({
    DateTime? startDate,
    DateTime? endDate,
    String? roomNumber,
    String? bedNumber,
    String? residentName,
    String? performedBy,
    String? detectionType,
    _i2.IncidentStatus? status,
    int? limit = 20,
    int? offset = 0,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#searchIncidents, [], {
              #startDate: startDate,
              #endDate: endDate,
              #roomNumber: roomNumber,
              #bedNumber: bedNumber,
              #residentName: residentName,
              #performedBy: performedBy,
              #detectionType: detectionType,
              #status: status,
              #limit: limit,
              #offset: offset,
            }),
            returnValue: _i4.Future<List<_i2.Incident>>.value(<_i2.Incident>[]),
          )
          as _i4.Future<List<_i2.Incident>>);

  @override
  _i4.Future<int> countIncidents() =>
      (super.noSuchMethod(
            Invocation.method(#countIncidents, []),
            returnValue: _i4.Future<int>.value(0),
          )
          as _i4.Future<int>);

  @override
  _i4.Future<int> countSearchResults({
    DateTime? startDate,
    DateTime? endDate,
    String? roomNumber,
    String? bedNumber,
    String? residentName,
    String? performedBy,
    String? detectionType,
    _i2.IncidentStatus? status,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#countSearchResults, [], {
              #startDate: startDate,
              #endDate: endDate,
              #roomNumber: roomNumber,
              #bedNumber: bedNumber,
              #residentName: residentName,
              #performedBy: performedBy,
              #detectionType: detectionType,
              #status: status,
            }),
            returnValue: _i4.Future<int>.value(0),
          )
          as _i4.Future<int>);
}
