version: '3'
services:
  docusaurus:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
#    volumes:
#      - .:/app
    working_dir: /app
    command: npm run serve -- --host 0.0.0.0
