// Mocks generated by Mockito 5.4.6 from annotations
// in mamoai/test/features/incident_history/presentation/blocs/incident_history_bloc_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;

import 'package:dartz/dartz.dart' as _i3;
import 'package:mamoai/core/error/failures.dart' as _i7;
import 'package:mamoai/features/incident_history/application/usecases/get_incidents_usecase.dart'
    as _i5;
import 'package:mamoai/features/incident_history/application/usecases/get_video_usecase.dart'
    as _i8;
import 'package:mamoai/features/incident_history/domain/repositories/i_incident_repository.dart'
    as _i2;
import 'package:mamoai/features/incident_history/domain/repositories/i_video_repository.dart'
    as _i4;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeIIncidentRepository_0 extends _i1.SmartFake
    implements _i2.IIncidentRepository {
  _FakeIIncidentRepository_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeEither_1<L, R> extends _i1.SmartFake implements _i3.Either<L, R> {
  _FakeEither_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeIVideoRepository_2 extends _i1.SmartFake
    implements _i4.IVideoRepository {
  _FakeIVideoRepository_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [GetIncidentsUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetIncidentsUseCase extends _i1.Mock
    implements _i5.GetIncidentsUseCase {
  MockGetIncidentsUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.IIncidentRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeIIncidentRepository_0(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i2.IIncidentRepository);

  @override
  _i6.Future<_i3.Either<_i7.Failure, _i2.IncidentListResult>> call(
    _i5.GetIncidentsParams? params,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#call, [params]),
            returnValue:
                _i6.Future<
                  _i3.Either<_i7.Failure, _i2.IncidentListResult>
                >.value(
                  _FakeEither_1<_i7.Failure, _i2.IncidentListResult>(
                    this,
                    Invocation.method(#call, [params]),
                  ),
                ),
          )
          as _i6.Future<_i3.Either<_i7.Failure, _i2.IncidentListResult>>);
}

/// A class which mocks [GetVideoUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetVideoUseCase extends _i1.Mock implements _i8.GetVideoUseCase {
  MockGetVideoUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.IVideoRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeIVideoRepository_2(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i4.IVideoRepository);

  @override
  _i6.Future<_i3.Either<_i7.Failure, String>> call(
    _i8.GetVideoParams? params,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#call, [params]),
            returnValue: _i6.Future<_i3.Either<_i7.Failure, String>>.value(
              _FakeEither_1<_i7.Failure, String>(
                this,
                Invocation.method(#call, [params]),
              ),
            ),
          )
          as _i6.Future<_i3.Either<_i7.Failure, String>>);
}
